collections:
  authors:
    output: true

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      permalink: /posts/:title/index.html
      isBlog: true
  - scope:
      path: ""
    values:
      layout: "default"

exclude: ["pure-release-1.0.0", "*.swp", "Session.vim", "README.md", "Gemfile", "Gemfile.lock", "line-icons", "favicon.png", "upload_to_s3.sh", "test.sh", "bitbucket-pipelines.yml", "Dockerfile", "invalidate_cache.sh*"]

url: https://techorrect.com

pagination:
  enabled: true
  indexpage: "index"
  per_page: 5
  permalink: '/page/:num/'
  extension: 
  title: ':title - page :num of :max'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
  trail: 
      before: 2
      after: 2
