collections:
  authors:
    output: true

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

exclude: ["pure-release-1.0.0", "*.swp", "Session.vim", "README.md", "Gemfile", "Gemfile.lock", "line-icons", "favicon.png", "upload_to_s3.sh"]
