image: ruby:2.4.3

pipelines:
  branches:
    master:
      - step:
          caches:
            - bundler
          script:
            - export LANG=C.UTF-8
            - export LANGUAGE=C.UTF-8
            - export LC_ALL=C.UTF-8
            - bundle install
            - JEKYLL_ENV=production bundle exec jekyll build
            - bundle exec htmlproofer _site/ --http-status-ignore "999" --check-html --trace

definitions:
  caches:
    bundler: ./vendor
